local cfg  = require("config")
local lang = require("lang")

local function log(s) print("[ResourceRespawn] " .. s .. "\n") end

math.randomseed(os.time())

-- ===== Resource map =====
-- key   = menu/config id (also the localization key in lang.lua)
-- sub   = substring matched against the actor class name (case-insensitive)
-- group = rarity label, kept only for ordering/reference (not used for timing)
-- supported = false -> listed in the menu for awareness but never acts
local RESOURCES = {
    -- Common
    { key = "Titanium",  sub = "titanium",  group = "Common" },
    { key = "Copper",    sub = "copper",    group = "Common" },
    { key = "Quartz",    sub = "quartz",    group = "Common" },
    { key = "Salt",      sub = "salt",      group = "Common" },
    { key = "WaterSlug", sub = "waterslug", group = "Common" },
    -- Medium
    { key = "Lead",      sub = "lead",      group = "Medium" },
    { key = "Silver",    sub = "silver",    group = "Medium" },
    { key = "Sulfur",    sub = "sulfur",    group = "Medium" },
    { key = "Gold",      sub = "gold",      group = "Medium" },
    { key = "Lithium",   sub = "lithium_",  group = "Medium" },  -- "lithium_" skips LithiumPearl (Clamthulu)
    -- Rare
    { key = "Atacamite",      sub = "atacamite",   group = "Rare" },
    { key = "Celestine",      sub = "celestine",   group = "Rare" },
    { key = "ConduitCrystal", sub = "fulgurite",   group = "Rare" },  -- node class is "Fulgurite"
    { key = "CreatureEnamel", sub = "needleshark", group = "Rare" },  -- node class is "NeedleSharkNeedles"
    -- Special (finite resources that normally never respawn)
    { key = "AxumCulture", sub = "axum",     group = "Special" },  -- node class is "AxumBioprintCulture_Cage"
    -- Listed for awareness but NOT functional: Troilite's "Mineralized Clinker" is a
    -- StaticMeshActor (no bHasBeenGathered flag), so the mod cannot reset it.
    { key = "Troilite",    sub = "troilite", group = "Special", supported = false },
}

-- Prefix used to make resource toggles look like sub-items of their group slider.
local SUB_PREFIX = "  \226\128\186 "  -- two spaces + "\u{203a}" (UTF-8 bytes) + space

-- ===== SN2ModSettings (in-game settings menu) =====
local MS_ROOT       = "./ue4ss/Mods/SN2ModSettings/"
local MS_ENABLED    = MS_ROOT .. "enabled.txt"
local MS_REG_PATH   = MS_ROOT .. "registrations/ResourceRespawn.lua"
local MS_SAVED_PATH = MS_ROOT .. "saved/ResourceRespawn.lua"

local function fileExists(path)
    local f = io.open(path, "r")
    if f then f:close() return true end
    return false
end

-- Load a lua file that returns a table -> returns the table, or nil
local function loadLuaTable(path)
    local f = io.open(path, "r")
    if not f then return nil end
    local content = f:read("*all")
    f:close()
    if not content or content == "" then return nil end
    local loader = load(content)
    if not loader then return nil end
    local ok, data = pcall(loader)
    if ok and type(data) == "table" then return data end
    return nil
end

-- Write the menu manifest for SN2ModSettings. Called at startup and again when
-- the game language changes (via lang.onRefresh) so the menu re-localizes.
local function writeRegistration()
    if not fileExists(MS_ENABLED) then return false end  -- SN2ModSettings not installed -> skip

    local parts = {
        "-- Auto-generated by ResourceRespawn. Do not edit by hand.\n",
        "return {\n",
        '    name = "ResourceRespawn",\n',
        string.format("    display = %q,\n", lang.s("display")),
        '    version = "1.0.0",\n',
        string.format("    description = %q,\n", lang.s("modDescription")),
        "    settings = {\n",
        string.format(
            '        { key="Enabled", title=%q, description=%q, type="toggle", default=true },\n',
            lang.s("enableTitle"), lang.s("enableDesc")),
    }

    -- One global respawn-time slider for every resource.
    parts[#parts + 1] = string.format(
        '        { key="RespawnSeconds", title=%q, description=%q,'
        .. ' type="slider", default=300, min=5, max=3600, step=5,'
        .. ' format="integer", enabled_by="Enabled" },\n',
        lang.s("timeTitle"), lang.s("timeDesc"))

    -- Per-resource toggles (flat list, in RESOURCES order).
    for _, r in ipairs(RESOURCES) do
        local title = SUB_PREFIX .. lang.res(r.key, "title")
        local desc  = lang.res(r.key, "desc")
        if r.supported == false then
            parts[#parts + 1] = string.format(
                '        { key=%q, title=%q, description=%q,'
                .. ' type="toggle", default=false, enabled_by="Enabled" },\n',
                r.key, title .. lang.s("unsupportedSuffix"), lang.s("unsupportedNote") .. desc)
        else
            parts[#parts + 1] = string.format(
                '        { key=%q, title=%q, description=%q,'
                .. ' type="toggle", default=true, enabled_by="Enabled" },\n',
                r.key, title, desc)
        end
    end

    parts[#parts + 1] = string.format(
        '        { key="DebugListNames", title=%q, description=%q,'
        .. ' type="toggle", default=false, enabled_by="Enabled" },\n',
        lang.s("debugTitle"), lang.s("debugDesc"))
    parts[#parts + 1] = "    },\n}\n"

    local f = io.open(MS_REG_PATH, "w")
    if not f then return false end
    f:write(table.concat(parts))
    f:close()
    return true
end

-- Re-localize the menu whenever the game language changes.
lang.onRefresh = writeRegistration

local hasModSettings = writeRegistration()

-- Merge settings: config.lua defaults, overridden by the in-game menu (saved) if present
local function currentSettings()
    local saved = hasModSettings and loadLuaTable(MS_SAVED_PATH) or nil

    local function pick(key, fallback)
        if saved and saved[key] ~= nil then return saved[key] end
        return fallback
    end

    local enabled = pick("Enabled", true)

    -- Single global respawn time for all resources.
    local def = cfg.RespawnSeconds or 300
    local seconds = tonumber(pick("RespawnSeconds", def)) or def
    if seconds < 1 then seconds = 1 end

    -- Build the list of enabled resources, all sharing the global respawn time.
    -- Unsupported entries (supported == false) are listed in the menu only and never act.
    local active = {}
    if enabled then
        for _, r in ipairs(RESOURCES) do
            if r.supported ~= false then
                local rdef = (cfg.Resources and cfg.Resources[r.key])
                if rdef == nil then rdef = true end
                if pick(r.key, rdef) then
                    active[#active + 1] = { sub = r.sub, seconds = seconds }
                end
            end
        end
    end

    local debug = pick("DebugListNames", cfg.DebugListNames)

    return { enabled = enabled, active = active, debug = debug }
end

-- ===== Respawn logic =====
local picked = {}
local seenNames = {}
local staticDone = {}  -- addresses of mined static nodes already reset (avoid live re-fighting)

-- Mined outcrops keep their "gathered" state authoritatively: resetting them live
-- makes the game re-hide them within a scan or two (flicker). For these we reset
-- once and stop; they reappear on the next area reload. Loose pickups don't.
local function isStaticNode(name)
    local low = name:lower()
    return low:find("resourcedeposit", 1, true) ~= nil
        or low:find("resourcenode", 1, true) ~= nil
end

local function className(a)
    local n = ""
    pcall(function() n = a:GetClass():GetFName():ToString() end)
    return n
end

-- Returns the respawn time (seconds) if the name matches an enabled resource, else nil
local function matchSeconds(name, active)
    local low = name:lower()
    for _, e in ipairs(active) do
        if low:find(e.sub, 1, true) ~= nil then return e.seconds end
    end
    return nil
end

local function newGuid(a)
    pcall(function()
        local g = a.ResourceId
        g.A = math.random(-2147483648, 2147483647)
        g.B = math.random(-2147483648, 2147483647)
        g.C = math.random(-2147483648, 2147483647)
        g.D = math.random(-2147483648, 2147483647)
    end)
end

-- Reset a gathered resource so the game treats it as fresh. Loose pickups and
-- water slugs re-render live; mined static nodes/deposits come back the next time
-- the area reloads (sleep / save-reload / re-stream) thanks to the new ResourceId.
local function bringBack(a)
    newGuid(a)
    pcall(function() a.bHasBeenGathered = false end)
    pcall(function() a:OnRep_HasBeenGathered() end)
    pcall(function() a:OnHasBeenGathered() end)
    pcall(function() a:ShowSkeletalMesh() end)
end

-- ===== DEEP SCAN (temporary diagnostic) =====
-- Logs the class names of the actors NEAREST to the player. Used to discover the
-- real class name of a resource whose display name does not appear in the class
-- name. Distance-sorted, so it is scale-independent.
-- Toggle with cfg.DeepScan in config.lua. Turn it off when done (costs performance).
local deepReported = false

local function playerLocation()
    local pc = FindFirstOf("PlayerController")
    if not pc then return nil end
    local pawn
    pcall(function() pawn = pc.Pawn end)
    if not pawn then return nil end
    local loc
    if pcall(function() loc = pawn:K2_GetActorLocation() end) and loc then
        return loc.X, loc.Y, loc.Z
    end
    return nil
end

local function deepScan()
    local actors = FindAllOf("Actor") or {}
    local px, py, pz = playerLocation()
    if not px then
        if not deepReported then deepReported = true; log("DEEPSCAN: player location not ready yet") end
        return
    end

    -- Collect world actors, skipping the player-attached cluster (< 2m) and
    -- gameplay-cue effect actors ("GC_" prefix), then sort by distance.
    local list = {}
    for _, a in ipairs(actors) do
        local loc
        if pcall(function() loc = a:K2_GetActorLocation() end) and loc then
            local dx, dy, dz = loc.X - px, loc.Y - py, loc.Z - pz
            local d2 = dx * dx + dy * dy + dz * dz
            if d2 >= 40000 then  -- skip everything within ~2m (held tools, vehicle, body)
                local n = ""
                pcall(function() n = a:GetClass():GetFName():ToString() end)
                if n ~= "" and n:sub(1, 3) ~= "GC_" then
                    list[#list + 1] = { d2 = d2, n = n }
                end
            end
        end
    end
    table.sort(list, function(p, q) return p.d2 < q.d2 end)

    if not deepReported then
        deepReported = true
        log("DEEPSCAN: " .. #actors .. " actors scanned")
    end

    -- One line per scan: the 10 nearest world actors with distances.
    local k = math.min(10, #list)
    local line = "NEAREST:"
    for i = 1, k do
        line = line .. "  [" .. math.floor(math.sqrt(list[i].d2) / 100) .. "m]" .. list[i].n
    end
    log(line)
end

local function tick()
    local s = currentSettings()
    if not s.enabled then return end

    if cfg.DeepScan then pcall(deepScan) end

    local now = os.time()
    for _, a in ipairs(FindAllOf("UWEWorldPopResourceBaseActor") or {}) do
        local ok, valid = pcall(function() return a:IsValid() end)
        if ok and valid then
            local name = className(a)

            if s.debug and name ~= "" and not seenNames[name] then
                seenNames[name] = true
                log("found resource class: " .. name)
            end

            local cooldown = matchSeconds(name, s.active)
            if cooldown then
                local addr = tostring(a:GetAddress())
                local staticNode = isStaticNode(name)
                -- A static node we've already reset: leave it alone so we don't
                -- fight the game's re-gathering (which causes flicker).
                if not (staticNode and staticDone[addr]) then
                    local g
                    pcall(function() g = a.bHasBeenGathered end)
                    if g == true then
                        local t = picked[addr]
                        if not t then
                            picked[addr] = now
                        elseif now - t >= cooldown then
                            bringBack(a)
                            picked[addr] = nil
                            if staticNode then staticDone[addr] = true end
                        end
                    elseif g == false then
                        picked[addr] = nil
                    end
                end
            end
        end
    end
end

LoopAsync(cfg.CheckIntervalMs, function()
    ExecuteInGameThread(function() pcall(tick) end)
    return false
end)

if hasModSettings then
    log("ready v1.0.0 (lang=" .. lang.code .. ", SN2ModSettings detected — adjust in the in-game menu)")
else
    log("ready v1.0.0 (lang=" .. lang.code .. ", using config.lua — SN2ModSettings not found)")
end
